package domain

// CREATE TABLE "Categories" (
//   "categoryID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   "name" varchar(100)
// );

type Category struct {
	categoryID int64
	Name       string
}
