package domain

import "time"

// CREATE TABLE "Customers" (
//   "customerID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   "name" varchar(100),
//   "email" email,
//   "password" password,
//   "created_at" timestamp,
//   "updated_at" timestamp
// );

type Customer struct {
	customerID int64
	name       string
	email      string
	password   string
	created_at time.Time
	updated_at time.Time
}
