package domain

import "time"

// CREATE TABLE "Customers" (
//   "customerID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   "name" varchar(100),
//   "email" email,
//   "password" password,
//   "created_at" timestamp,
//   "updated_at" timestamp
// );

type Customer struct {
	CustomerID int64     `json:"customerID"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
	Password   string    `json:"password"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
