package domain

import "time"

// CREATE TABLE "Games" (
//   "gameID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   "categoryID" int,
//   "titles" varchar(100),
//   "price" float64,
//   "created_at" timestamp,
//   "updated_at" timestamp
// );

type Game struct {
	gameID     int64
	categoryID int64
	titles     string
	price      float64
	created_at time.Time
	updated_at time.Time
}
