package domain

import "time"

// CREATE TABLE "Games" (
//   "gameID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   "categoryID" int,
//   "titles" varchar(100),
//   "price" float64,
//   "created_at" timestamp,
//   "updated_at" timestamp
// );

type Game struct {
	GameID     int64
	CategoryID int64
	Title      string
	Price      float64
	Created_at time.Time
	Updated_at time.Time
}
