package domain

import "time"

// CREATE TABLE "Orders" (
//   "orderID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   "customerID" int,
//   "gameID" int,
//   "created_at" timestamp
// );

type Order struct {
	OrderID    int64
	CustomerID int64
	GameID     int64
	GameTitle  string
	GamePrice  float64
	CreatedAt  time.Time
}
