package domain

import "time"

// CREATE TABLE "Orders" (
//   "orderID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   "customerID" int,
//   "gameID" int,
//   "created_at" timestamp
// );

type Order struct {
	orderID    int64
	customerID int64
	gameID     int64
	created_at time.Time
}
