package domain

import "time"

// CREATE TABLE "Payments" (
//   "paymentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   "orderID" int,
//   "amount" float64,
//   "status" varchar(50),
//   "created_at" timestamp
// );

type Payment struct {
	paymentID  int64
	orderID    int64
	amount     float64
	status     string
	created_at time.Time
}
