package domain

import "time"

// CREATE TABLE "Payments" (
//   "paymentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   "orderID" int,
//   "amount" float64,
//   "status" varchar(50),
//   "created_at" timestamp
// );

type Payment struct {
	PaymentID  int64
	CustomerID int64
	Amount     float64
	Status     string
	CreatedAt  time.Time
}
