CREATE TABLE "Customers" (
  "customerID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "email" email,
  "password" password,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "Games" (
  "gameID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoryID" int,
  "titles" varchar(100),
  "price" float64,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "Categories" (
  "categoryID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100)
);

CREATE TABLE "Orders" (
  "orderID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customerID" int,
  "gameID" int,
  "created_at" timestamp
);

CREATE TABLE "Payments" (
  "paymentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderID" int,
  "amount" float64,
  "status" varchar(50),
  "created_at" timestamp
);

ALTER TABLE "Games" ADD FOREIGN KEY ("categoryID") REFERENCES "Categories" ("categoryID");

ALTER TABLE "Orders" ADD FOREIGN KEY ("customerID") REFERENCES "Customers" ("customerID");

ALTER TABLE "Orders" ADD FOREIGN KEY ("gameID") REFERENCES "Games" ("gameID");

ALTER TABLE "Payments" ADD FOREIGN KEY ("orderID") REFERENCES "Orders" ("orderID");
